name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: centos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v3.0.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.SERVER_USERNAME }}
          hostname: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          local-path: .
          remote-path: /etc/ansible
          exclude: |
            exclude_pattern_1
            exclude_pattern_2
