name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo yum update
        sudo yum install -y sshpass
    - name: Deploy to Production
      uses: easingthemes/ssh-deploy@v2.3.1
      with:
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        ssh_username: ${{ secrets.USERNAME }}
        server_ip: 192.168.100.80
        server_port: 22
        local_path: '.'
        server_path: '/path/to/server/directory'
        args: '-rltgoDzvO --delete'
      env:
        OS: 'rockyos'
