deploy: update

on:
  push:
    tags:

jobs:
  build:

    steps:
  
     -name: update
      with:
        host: ${{ secrets.MY_HOST }}
        port: ${{ secrets.MY_PORT }}
        username: ${{ secrets.MY_NAME }}
        password: ${{ secrets.MY_PASS }}
        ssh: ${{ secrets.MY_SSH }}

      run: cd ansible
