- name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.192.168.100.80}}
          username: ${{ secrets.root }}
          key: ${{ secrets.MY_SSH }}
          port: ${{ secrets.22 }}
          script: |
            whoami
            git pull origin master
