name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: centos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2

    - name: Install dependencies
      run: |
        sudo yum update
        sudo yum install -y python3-pip
        pip3 install -r requirements.txt
    - name: Build and test
      run: |
        python3 build.py
        python3 test.py
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v3.0.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        args: |
          --delete
          --exclude 'node_modules'
          --exclude '.env'
        host: 192.168.100.80
        username: root
        port: 22
        local-path: './dist'
        remote-path: '/var/www/html'
