name: Deploy to Rocky Linux Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: <192.168.100.80>
          username: <root>
          key: ${{ secrets.my_ssh }}
          script: |
            cd ansible
            git pull
            # Run any other commands to deploy your project
