name: Hello world

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VMware
        uses: vmware-actions/setup-vmware@v1
        with:
          hostname: 192.168.100.230
          username: seongjae
          password: thdtjdwo257!
