name: update

on:
  push:
  pull_request:

jobs:
  build_and_test :
    runs-on: centos-latest

    steps:
      - name: npm
        run: sudo yum install npm -y

      - name: cd
        run: cd /home/   
