name: update

on: [push]
  
jobs:
  build_and_test :

    runs-on: centos-latest

    steps:
    #- uses: actions/checkout@v2
      - name: npm
        run: sudo yum install npm -y

      - name: cd
        run: cd /home/   
