name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo yum install -y nodejs
      run: npm install

    - name: Build
      run: npm run build

  test:
    name: Test
    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo yum install -y nodejs
      run: npm install

    - name: Test
      run: npm run test

  deploy:
    name: Deploy
    runs-on: centos-latest
    needs: [build, test]

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        git config user.name "${{ secrets.DEPLOY_USER }}"
        git config user.email "${{ secrets.DEPLOY_EMAIL }}"
        git add .
        git commit -m "Deploy to production"
        git push -u origin main
