name: ssh

on: [push]
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          key: ${{ secrets.MY_SSH }} 
          port: ${{ secrets.MY_PORT }}
          script: whoami
