name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
      - name: Use Node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: sudo apt-get npm install
      - name: Build and test
        run: sudo apt-get npm run build
