name: Deploy to VMWare Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0

    - name: Install Ansible
      run: sudo apt install -y ansible

    - name: Run Ansible Playbook
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.100.80
        username: root
        password: ${{ secrets.MY_SSH }}
        port: 22
        script: |
          cd ansible
          ansible-playbook vmware.yml
