name: Deploy to Rocky OS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.2.12
      env:
        SSH_PRIVATE_KEY: ${{ secrets.MY_SSH }}
        ARGS: "-rltgoDzvO --delete" # Optional, pass additional arguments to rsync
      with:
        server: ${{ secrets.MY_HOST }}
        username: ${{ secrets.MY_USERNAME }}
        port: ${{ secrets.MY_PORT }}
        remote_path: ${{ secrets.REMOTE_PATH }}
     
