name: Deploy to Rocky OS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v3.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.MY_SSH }}
        SSH_DEPLOY_DEBUG: true
      with:
       REMOTE_HOST: ${{ secrets.MY_HOST }}
       REMOTE_USER: ${{ secrets.MY_USERNAME }}
       REMOTE_PASSWORD: ${{ secrets.MY_PASS }}
       REMOTE_PORT: ${{ secrets.MY_PORT }}
       SSH_PRIVATE_KEY: ${{ secrets.MY_SSH }}
       SOURCE: /root/test
       TARGET: ${{ secrets.REMOTE_PATH }}
     
