name: Deploy to Rocky OS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v3.1.1
      env:
        ARGS: "-rltgoDzvO --delete" # Optional, pass additional arguments to rsync
        SSH_DEPLOY_DEBUG: true
      with:
       REMOTE_HOST: ${{ secrets.MY_HOST }}
       REMOTE_USER: ${{ secrets.MY_USERNAME }}
       REMOTE_PORT: ${{ secrets.MY_PORT }}
       SSH_PASSWORD: ${{ secrets.GIT_TOKEN }}
       SOURCE: 'test/'
       TARGET: ${{ secrets.REMOTE_PATH }}
